---
- name: Install and start the services
  hosts: all

  tasks:
   - name: Installing Nginx web server
     yum:
      name: nginx
      state: present
   - name:
     service:
       name: nginx
       state: started
       enabled: true

